/// Certificate loading for the mock server.
///
/// Certs are throwaway fixtures generated by tool/gen_certs.sh into the gitignored
/// `certs/` directory. They must never be committed (docs/PLAN.md 2.2). This
/// helper just reads them off disk and gives a clear error if they are missing.
library;

import 'dart:io';

class MockCerts {
  MockCerts({
    required this.caCert,
    required this.serverCert,
    required this.serverKey,
    required this.clientCert,
    required this.clientKey,
  });

  final List<int> caCert;
  final List<int> serverCert;
  final List<int> serverKey;
  final List<int> clientCert;
  final List<int> clientKey;

  /// Loads CA cert, server cert/key, and client cert/key from [dir]
  /// (default `certs/`).
  static MockCerts load({String dir = 'certs'}) {
    File f(String name) => File('$dir/$name');
    final ca = f('ca.pem');
    final cert = f('server.pem');
    final key = f('server.key');
    final clientCert = f('client.pem');
    final clientKey = f('client.key');
    for (final file in [ca, cert, key, clientCert, clientKey]) {
      if (!file.existsSync()) {
        throw StateError(
          'Missing ${file.path}. Generate throwaway certs first:\n'
          '  bash tool/gen_certs.sh\n'
          '(certs/ is gitignored and must never be committed.)',
        );
      }
    }
    return MockCerts(
      caCert: ca.readAsBytesSync(),
      serverCert: cert.readAsBytesSync(),
      serverKey: key.readAsBytesSync(),
      clientCert: clientCert.readAsBytesSync(),
      clientKey: clientKey.readAsBytesSync(),
    );
  }
}
