#!/usr/bin/env bash
# Lock / unlock the Stride release signing keystore.
#
# WHY THIS EXISTS
# ---------------
# Stride updates itself over the air. Android will only accept an update signed with the SAME key
# as the installed copy, so this one key is what makes every future update possible. Two failure
# modes, both permanent, pull in opposite directions:
#
#   lose it     -> no console can ever be updated again. The only recovery is uninstall +
#                  reinstall, on a machine that may be in someone's basement.
#   leak it     -> anyone can sign an APK that every Stride console will accept as a genuine
#                  update. This is the whole ballgame; there is no revocation.
#
# So the key lives in the repo (survives a dead laptop, versioned, always findable) but only ever
# as ciphertext. The passphrase is the secret, and it never goes in git.
#
# The passphrase lives in the macOS login keychain under the service name below. Put a copy in a
# password manager too - if you lose the keychain AND the password manager, see failure mode one.
#
#   tools/keystore.sh unlock   # .enc -> .jks + key.properties, ready to build
#   tools/keystore.sh lock     # re-encrypt after a rotation, then remove the plaintext
#   tools/keystore.sh status   # what exists, and the signing fingerprint
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KS="$ROOT/keystore/stride-release.jks"
ENC="$KS.enc"
PROPS="$ROOT/apps/spikes/android/key.properties"
ALIAS="stride"
KEYCHAIN_SERVICE="stride-release-keystore"

# 600k iterations is deliberate: the ciphertext is public-ish (anyone with repo access holds it),
# so the passphrase is the only thing standing between them and the signing key.
ITER=600000

die() { echo "error: $*" >&2; exit 1; }

# A keystore that openssl decrypted without complaint can still be garbage - a wrong-but-lucky
# passphrase, a truncated file, a corrupted blob. Ask keytool whether it is really a keystore
# containing our alias before anything relies on it. This is the guard that stops a bad plaintext
# from being encrypted back over a good .enc.
assert_keystore() {
  keytool -list -keystore "$1" -alias "$ALIAS" -storepass "$(get_pass)" >/dev/null 2>&1
}

get_pass() {
  if [[ -n "${STRIDE_KEYSTORE_PASS:-}" ]]; then
    printf '%s' "$STRIDE_KEYSTORE_PASS"
    return
  fi
  security find-generic-password -a stride-release -s "$KEYCHAIN_SERVICE" -w 2>/dev/null && return
  die "no passphrase. Set STRIDE_KEYSTORE_PASS, or restore it to the keychain:
  security add-generic-password -a stride-release -s $KEYCHAIN_SERVICE -w"
}

case "${1:-}" in
  unlock)
    [[ -f "$ENC" ]] || die "missing $ENC"
    PASS="$(get_pass)"
    # openssl writes the output file before it discovers the passphrase is wrong, leaving a
    # truncated .jks behind. That file is poison: `lock` would later encrypt it back over the good
    # ciphertext and destroy the only copy of the signing key. Remove it on any failure.
    if ! openssl enc -d -aes-256-cbc -pbkdf2 -iter "$ITER" -in "$ENC" -out "$KS" -pass pass:"$PASS" 2>/dev/null; then
      rm -f "$KS"
      die "decrypt failed - wrong passphrase?"
    fi
    assert_keystore "$KS" || { rm -f "$KS"; die "decrypted file is not a valid keystore"; }
    # Written every time rather than only when absent: a stale key.properties pointing at an old
    # path or alias fails at signing time with a far less obvious message.
    cat > "$PROPS" <<EOF
# GENERATED by tools/keystore.sh - gitignored, do not commit.
storeFile=$KS
storePassword=$PASS
keyAlias=$ALIAS
keyPassword=$PASS
EOF
    chmod 600 "$PROPS" "$KS"
    echo "unlocked. release builds will now be signed with the Stride release key."
    ;;
  lock)
    [[ -f "$KS" ]] || die "missing $KS - nothing to lock"
    PASS="$(get_pass)"
    # Refuse to encrypt a plaintext that is not a real keystore. Without this, a corrupt .jks
    # (see `unlock`) would be encrypted over the good ciphertext and the key would be gone.
    assert_keystore "$KS" || die "$KS is not a valid keystore - refusing to encrypt it over $ENC"
    openssl enc -aes-256-cbc -pbkdf2 -iter "$ITER" -salt -in "$KS" -out "$ENC" -pass pass:"$PASS"
    # Verify before deleting the only plaintext copy. Encrypting to a corrupt file and then
    # removing the original would destroy the key silently.
    TMP="$(mktemp)"
    openssl enc -d -aes-256-cbc -pbkdf2 -iter "$ITER" -in "$ENC" -out "$TMP" -pass pass:"$PASS"
    cmp -s "$KS" "$TMP" || { rm -f "$TMP"; die "re-encrypted file does not round-trip - keeping plaintext"; }
    rm -f "$TMP" "$KS" "$PROPS"
    echo "locked. $ENC is safe to commit; plaintext removed."
    ;;
  status)
    echo "encrypted : $([[ -f "$ENC" ]] && echo present || echo MISSING)"
    echo "plaintext : $([[ -f "$KS" ]] && echo "present (run 'lock' before committing)" || echo absent)"
    echo "properties: $([[ -f "$PROPS" ]] && echo present || echo absent)"
    if [[ -f "$KS" ]]; then
      keytool -list -v -keystore "$KS" -alias "$ALIAS" -storepass "$(get_pass)" 2>/dev/null \
        | grep -i "SHA256:" | head -1
    fi
    ;;
  *)
    echo "usage: tools/keystore.sh {unlock|lock|status}" >&2
    exit 2
    ;;
esac
